

export const metadata = {
  title: "Admin Panel",
  description: "Generated by Hiren ray",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=""
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
