import AdminHeader from "@/component/admin/layout/AdminHeader";
import AdminProtector from "@/services/protect/AdminProtector";


export const metadata = {
  title: "Admin Panel",
  description: "Generated by Hiren ray",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className=""
    >
      <header>
        <AdminHeader/>
      </header>
      <body className="min-h-full flex flex-col "><AdminProtector>{children}</AdminProtector></body>
    </html>
  );
}
